[package]
name = "wincms"
version = "0.1.0"
authors = ["Dmitry Pankratov <dmitry@everyoneprint.com>"]
edition = "2021"

[dependencies]
windows = { version = "0.28", features = ["alloc", "Win32_Foundation", "Win32_Security_Cryptography"] }
widestring = "1.0.0-beta.1"
log = "0.4"
