[package]
name = "wincms"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.37", features = [
    "alloc", "Win32_Foundation", "Win32_Security_Cryptography"] }
widestring = "1"
log = "0.4"

[dev-dependencies]
sha2 = "0.10"
