[package]
name = "wincms"
version = "0.1.0"
authors = ["Dmitry Pankratov <dmitry@everyoneprint.com>"]
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["wincrypt", "ncrypt", "errhandlingapi", "winerror"] }
widestring = "0.4"
log = "0.4"
